# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-17 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donorregistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=8)),
                ('Confirm_Password', models.CharField(max_length=8)),
                ('Weight', models.FloatField(max_length=3)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone_Mobile', models.CharField(max_length=10)),
                ('Phone_Office', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='inspiringstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.IntegerField(max_length=10)),
                ('Story', models.CharField(max_length=150)),
            ],
        ),
    ]
