# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_auto_20180428_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregistration',
            name='Blood_Group',
            field=models.CharField(default='123', max_length=10),
        ),
    ]
