# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_donorregistration_blood_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
