# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorregistration',
            name='Age',
            field=models.IntegerField(default='18', max_length=3),
        ),
        migrations.AddField(
            model_name='donorregistration',
            name='Pincode',
            field=models.IntegerField(default='123', max_length=10),
        ),
    ]
