# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_auto_20180508_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donorregistration',
            new_name='User',
        ),
    ]
