# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-14 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_auto_20180514_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
    ]
