# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-17 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0011_auto_20180514_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='District',
            field=models.CharField(default='pathankot', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='State',
            field=models.CharField(default='punjab', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age',
            field=models.IntegerField(default='18'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Weight',
            field=models.FloatField(),
        ),
    ]
