# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_auto_20180517_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Pincode',
        ),
        migrations.AddField(
            model_name='user',
            name='City',
            field=models.CharField(default='pathankot', max_length=10),
        ),
    ]
